version: '3.6'

volumes:
  files:

services:

  ftp:
    image: rhrn/vsftpd
    environment:
      - PASSWORD=FSBhuNOR
    ports:
      - '21000:21'
      - '20000:20000'
    volumes:
      #- /path/to/cert.pem:/etc/vsftpd/vsftpd.pem
      - files:/home/files
